### ISSUE TITLE
Can't get the right json file by using the given test cases.

### ISSUE THREAD

**Issue by Heero7Yuy** [LucasMFreire/assert-p4#2]
Hi, I've tried compile the given test cases using the command:
`p4c-bm2-ss ./ts_switching-16.p4 --toJSON ./output.json`
then I got a json file, but when I translate the json to C, it shows that:
`AttributeError: 'Node' object has no attribute 'declarations'` 
I've found my json file's first node has attribute 'objects', and the given file's first node has attribute 'declarations'.
So I think the reason of this problem is our P4C compile versions are different, so can you tell me what is your P4C version and your protobuf version when you compile the .p4 file?

(my P4C version is 0.5, protobuf version is 3.6.0)

thx a lot

**Comment by LucasMFreire** [comment]
Hi Heero7Yuy. I am not working on assert-p4 anymore. The code and documentation are currently being improved [here](https://github.com/gnmartins/assert-p4).
