### ISSUE TITLE
AttributeError: 'Node' object has no attribute 'declarations'

### ISSUE THREAD

**Issue by alenashch** [LucasMFreire/assert-p4#5]
I was trying to use assert-p4 for the dapper. And I was able to convert p4 file into json file. But when i run 'python2 src/P4_to_C.py dapper.json' command I get AttributeError: 'Node' object has no attribute 'declarations'. 
Why do i run into this error?

**Comment by LucasMFreire** [comment]
Have you tried running it with this version?
https://github.com/gnmartins/assert-p4

**Comment by alenashch** [comment]
That is exactly the one i used

**Comment by LucasMFreire** [comment]
It seems this case needs a closer look then. I'm not working on this project anymore, but you may try contacting the people mentioned on the repository above.

**Comment by alenashch** [comment]
I see, thank you!
